title: Helena Canever PhD, Data Scientist
email: helena.canever@gmail.com
description: Data Scientist with a biology background
github_username: HelenaCanever

author:
  name   : "Helena Canever"
  avatar : "/assets/images/11053304_10205763187672274_5855646528462490088_o.jpg"
  bio    : "Data Scientist with a background in cell biology and automatization of image analysis"
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/HelenaCanever"
    - label: "Linkedin"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/helenacanever"

remote_theme: 'mmistakes/minimal-mistakes@4.24.0'
plugins: 
- jekyll-include-cache


minimal_mistakes_skin: dirt
search: true


titles_from_headings:
  enabled:     true
  strip_title: true
  collections: true

    


