title: Helena Canever PhD, Data Scientist
description: Data Scientist with a biology background
remote_theme: 'mmistakes/minimal-mistakes@4.24.0'
plugins: 
- jekyll-include-cache

titles_from_headings:
  enabled:     true
  strip_title: true
  collections: true
  
sidebar:
  - title: "Helena Canever"
    image: "/assets/11053304_10205763187672274_5855646528462490088_o.jpg"
    image_alt: "image"
    text: "Cell Biologist with a strong experience in data analysis and modeling.\ Open to new opportunities in the world of Data Science."
    


